server:
  port: 8088

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:student;DB_CLOSE_DELAY=-1;
    username: sa
    password:

  flyway:
    user: sa
    password:
    url: jdbc:h2:mem:student;DB_CLOSE_DELAY=-1;

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
